### ISSUE TITLE
doesn't fail gracefully when there is no .renviron file

### ISSUE THREAD

**Issue by RMHogervorst** [hrbrmstr/rpwnd#1]
Hi Bob, 

I like the package, and the idea behind it,  but it fails on my work pc because I have no .renviron file (yet). It should probably not fail though.
```
I also have pretty broad filesystem access. In fact, I can see everthing you can, like your .Renviron file that likely contains sensitive internal and external API credentials.

Error : .onAttach failed in attachNamespace() for 'rpwnd', details:
  call: file(con, "r")
  error: cannot open the connection
In addition: Warning message:
In file(con, "r") :

```

**Comment by hrbrmstr** [comment]
Aye, thanks. It's a super alpha version created in like five minutes and
intended to solicit other evil volunteers 😀

**Comment by RMHogervorst** [comment]
/s evillaugh: "muahahahahaha!" (right) Maybe I'll try to whip up an improvement. Although I never thought about the implications like this shows (which is your whole point of course). 

Thanks!

**Comment by hrbrmstr** [comment]
does fail gracefully now :-)
